In [1]:
import httpx


def fetch_data(url: str):
    with httpx.Client() as client:
        try:
            response = client.get(url)
            response.raise_for_status()
            return response.json()
        except Exception as error:
            print(f"Error while fetching {url=}: {error}")


def get_data():
    base_url = "https://zenodo.org/api/records?communities=ssm-esr&size=25&page=1"
    data = fetch_data(base_url)
    return data

In [2]:
data = get_data()

In [3]:
data.keys()

dict_keys(['hits', 'aggregations', 'links'])

In [4]:
data.get("hits").keys()

dict_keys(['hits', 'total'])

In [9]:
example = data.get("hits", {}).get("hits")[2]

In [10]:
example

{'created': '2026-03-24T09:32:59.797412+00:00',
 'modified': '2026-04-21T16:27:50.162756+00:00',
 'id': 18984755,
 'conceptrecid': '18984754',
 'doi': '10.5281/zenodo.18984755',
 'conceptdoi': '10.5281/zenodo.18984754',
 'doi_url': 'https://doi.org/10.5281/zenodo.18984755',
 'metadata': {'title': "Le financement de la recherche et de l'enseignement supérieur par les collectivités territoriales entre 2023 et 2025",
  'doi': '10.5281/zenodo.18984755',
  'publication_date': '2026-03-24',
  'description': '<p>En 2024, les collectivit&eacute;s territoriales ont consacr&eacute; 1,5 milliard d&rsquo;euros (Md&euro;) au financement de l&rsquo;enseignement sup&eacute;rieur et de la recherche (ESR), en augmentation de 74 M&euro; par rapport &agrave; 2023. Elles ont d&eacute;pens&eacute; 714 M&euro; en faveur de la recherche et du transfert de technologie (R&amp;T), dont 35 % en aides en direction des entreprises innovantes et en transfert de technologie. Elles ont &eacute;galement d&eacute;pens&eacute; 743 M&euro; en faveur de l&rsquo;enseignement sup&eacute;rieur et de la vie &eacute;tudiante (ES&amp;VE), 48 % de ce budget ayant financ&eacute; des op&eacute;rations immobili&egrave;res.</p>',
  'access_right': 'open',
  'creators': [{'name': 'Béroud, Mallaury',
    'affiliation': "Ministère de l'Enseignement Supérieur et de la Recherche"}],
  'keywords': ['Territoires',
   'Enseignement supérieur',
   'Statistiques',
   'Finance',
   'Recherche',
   "Le financement de la recherche et de l'enseignement supérieur par les collectivités territoriales"],
  'resource_type': {'title': 'Journal article',
   'type': 'publication',
   'subtype': 'article'},
  'journal': {'issue': '26.05', 'title': 'Note flash SIES'},
  'alternate_identifiers': [{'identifier': '2729-1383'}],
  'license': {'id': 'cc-by-4.0'},
  'communities': [{'id': 'ssm-esr'}],
  'relations': {'version': [{'index': 0,
     'is_last': True,
     'parent': {'pid_type': 'recid', 'pid_value': '18984754'}}]}},
 'title': "Le financement de la recherche et de l'enseignement supérieur par les collectivités territoriales entre 2023 et 2025",
 'links': {'self': 'https://zenodo.org/api/records/18984755',
  'self_html': 'https://zenodo.org/records/18984755',
  'preview_html': 'https://zenodo.org/records/18984755?preview=1',
  'doi': 'https://doi.org/10.5281/zenodo.18984755',
  'self_doi': 'https://doi.org/10.5281/zenodo.18984755',
  'self_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.18984755',
  'reserve_doi': 'https://zenodo.org/api/records/18984755/draft/pids/doi',
  'parent': 'https://zenodo.org/api/records/18984754',
  'parent_html': 'https://zenodo.org/records/18984754',
  'parent_doi': 'https://doi.org/10.5281/zenodo.18984754',
  'parent_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.18984754',
  'self_iiif_manifest': 'https://zenodo.org/api/iiif/record:18984755/manifest',
  'self_iiif_sequence': 'https://zenodo.org/api/iiif/record:18984755/sequence/default',
  'files': 'https://zenodo.org/api/records/18984755/files',
  'media_files': 'https://zenodo.org/api/records/18984755/media-files',
  'thumbnails': {'10': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E10,/0/default.jpg',
   '50': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E50,/0/default.jpg',
   '100': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E100,/0/default.jpg',
   '250': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E250,/0/default.jpg',
   '750': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E750,/0/default.jpg',
   '1200': 'https://zenodo.org/api/iiif/record:18984755:1249.pdf/full/%5E1200,/0/default.jpg'},
  'archive': 'https://zenodo.org/api/records/18984755/files-archive',
  'archive_media': 'https://zenodo.org/api/records/18984755/media-files-archive',
  'latest': 'https://zenodo.org/api/records/18984755/versions/latest',
  'latest_html': 'https://zenodo.org/records/18984755/latest',
  'versions': 'https://zenodo.org/api/records/18984755/versions',
  'draft': 'https://zenodo.org/api/records/18984755/draft',
  'access_links': 'https://zenodo.org/api/records/18984755/access/links',
  'access_grants': 'https://zenodo.org/api/records/18984755/access/grants',
  'access_users': 'https://zenodo.org/api/records/18984755/access/users',
  'access_request': 'https://zenodo.org/api/records/18984755/access/request',
  'access': 'https://zenodo.org/api/records/18984755/access',
  'communities': 'https://zenodo.org/api/records/18984755/communities',
  'communities-suggestions': 'https://zenodo.org/api/records/18984755/communities-suggestions',
  'request_deletion': 'https://zenodo.org/api/records/18984755/request-deletion',
  'file_modification': 'https://zenodo.org/api/records/18984755/file-modification',
  'quota_increase': 'https://zenodo.org/api/records/18984755/quota-increase',
  'requests': 'https://zenodo.org/api/records/18984755/requests'},
 'updated': '2026-04-21T16:27:50.162756+00:00',
 'recid': '18984755',
 'revision': 5,
 'files': [{'id': '44763f9b-ccbc-481e-8aec-ddf1ac0b89a4',
   'key': '1249_1.xlsx',
   'size': 897966,
   'checksum': 'md5:1e032a654ae4ab748186f7855ca1546a',
   'links': {'self': 'https://zenodo.org/api/records/18984755/files/1249_1.xlsx/content'}},
  {'id': '1fd63c8c-5a65-47ae-9147-93e00b6af6df',
   'key': '1249.pdf',
   'size': 1093925,
   'checksum': 'md5:4757cd70dc57c2077d5add4fe0f0a554',
   'links': {'self': 'https://zenodo.org/api/records/18984755/files/1249.pdf/content'}}],
 'swh': None,
 'owners': [{'id': '1455544'}],
 'status': 'published',
 'stats': {'downloads': 7,
  'unique_downloads': 4,
  'views': 8,
  'unique_views': 6,
  'version_downloads': 7,
  'version_unique_downloads': 4,
  'version_unique_views': 6,
  'version_views': 8},
 'state': 'done',
 'submitted': True}

In [12]:
data.get("aggregations")

{'access_status': {'buckets': [{'key': 'open',
    'doc_count': 911,
    'label': 'Open',
    'is_selected': False}],
  'label': 'Access status'},
 'resource_type': {'buckets': [{'key': 'publication',
    'doc_count': 911,
    'label': 'Publication',
    'is_selected': False,
    'inner': {'buckets': [{'key': 'publication-article',
       'doc_count': 842,
       'label': 'Journal article',
       'is_selected': False},
      {'key': 'publication-book',
       'doc_count': 69,
       'label': 'Book',
       'is_selected': False}]}}],
  'label': 'Resource types'},
 'subject': {'buckets': [{'key': 'Emploi scientifique',
    'doc_count': 1,
    'label': 'Emploi scientifique',
    'is_selected': False}],
  'label': 'Subjects'},
 'file_type': {'buckets': [{'key': 'pdf',
    'doc_count': 893,
    'label': 'PDF',
    'is_selected': False},
   {'key': 'xlsx', 'doc_count': 115, 'label': 'XLSX', 'is_selected': False},
   {'key': 'txt', 'doc_count': 18, 'label': 'TXT', 'is_selected': False},
   {'key': 'xls', 'doc_count': 14, 'label': 'XLS', 'is_selected': False}],
  'label': 'File type'}}

In [13]:
data.get("links")

{'self': 'https://zenodo.org/api/records?communities=ssm-esr&page=1&size=25&sort=newest',
 'next': 'https://zenodo.org/api/records?communities=ssm-esr&page=2&size=25&sort=newest'}

In [30]:
data.get("hits").get("hits")[0]

{'created': '2026-03-27T09:45:30.042413+00:00',
 'modified': '2026-03-27T09:45:30.647460+00:00',
 'id': 18984935,
 'conceptrecid': '18984934',
 'doi': '10.5281/zenodo.18984935',
 'conceptdoi': '10.5281/zenodo.18984934',
 'doi_url': 'https://doi.org/10.5281/zenodo.18984935',
 'metadata': {'title': "L'activité de R&D selon les catégories d'entreprises en 2023 – résultats détaillés pour 2023",
  'doi': '10.5281/zenodo.18984935',
  'publication_date': '2026-03-26',
  'description': '<p>En 2023, les entreprises ont r&eacute;alis&eacute; 40,6 Md&euro; de d&eacute;penses int&eacute;rieures de recherche et de d&eacute;veloppement exp&eacute;rimental (DIRDE) en France. Avec 22,1 Md&euro;, les grandes entreprises (GE) sont &agrave; l&rsquo;origine de 54 % de la DIRDE. Leurs d&eacute;penses se concentrent essentiellement dans les branches industrielles. En revanche, les petites et moyennes entreprises (PME) concentrent une part importante de leurs d&eacute;penses int&eacute;rieures de R&amp;D dans les branches de services. Enfin l&rsquo;activit&eacute; de R&amp;D est plus d&eacute;velopp&eacute;e dans les entreprises exportatrices.</p>',
  'access_right': 'open',
  'creators': [{'name': 'Amoros, Pierre',
    'affiliation': "Ministère de l'Enseignement Supérieur et de la Recherche"}],
  'resource_type': {'title': 'Journal article',
   'type': 'publication',
   'subtype': 'article'},
  'journal': {'issue': '26.03', 'title': "Note d'information SIES"},
  'alternate_identifiers': [{'identifier': '2729-1383'}],
  'license': {'id': 'cc-by-4.0'},
  'communities': [{'id': 'ssm-esr'}],
  'relations': {'version': [{'index': 0,
     'is_last': True,
     'parent': {'pid_type': 'recid', 'pid_value': '18984934'}}]}},
 'title': "L'activité de R&D selon les catégories d'entreprises en 2023 – résultats détaillés pour 2023",
 'links': {'self': 'https://zenodo.org/api/records/18984935',
  'self_html': 'https://zenodo.org/records/18984935',
  'preview_html': 'https://zenodo.org/records/18984935?preview=1',
  'doi': 'https://doi.org/10.5281/zenodo.18984935',
  'self_doi': 'https://doi.org/10.5281/zenodo.18984935',
  'self_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.18984935',
  'reserve_doi': 'https://zenodo.org/api/records/18984935/draft/pids/doi',
  'parent': 'https://zenodo.org/api/records/18984934',
  'parent_html': 'https://zenodo.org/records/18984934',
  'parent_doi': 'https://doi.org/10.5281/zenodo.18984934',
  'parent_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.18984934',
  'self_iiif_manifest': 'https://zenodo.org/api/iiif/record:18984935/manifest',
  'self_iiif_sequence': 'https://zenodo.org/api/iiif/record:18984935/sequence/default',
  'files': 'https://zenodo.org/api/records/18984935/files',
  'media_files': 'https://zenodo.org/api/records/18984935/media-files',
  'thumbnails': {'10': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E10,/0/default.jpg',
   '50': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E50,/0/default.jpg',
   '100': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E100,/0/default.jpg',
   '250': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E250,/0/default.jpg',
   '750': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E750,/0/default.jpg',
   '1200': 'https://zenodo.org/api/iiif/record:18984935:1250.pdf/full/%5E1200,/0/default.jpg'},
  'archive': 'https://zenodo.org/api/records/18984935/files-archive',
  'archive_media': 'https://zenodo.org/api/records/18984935/media-files-archive',
  'latest': 'https://zenodo.org/api/records/18984935/versions/latest',
  'latest_html': 'https://zenodo.org/records/18984935/latest',
  'versions': 'https://zenodo.org/api/records/18984935/versions',
  'draft': 'https://zenodo.org/api/records/18984935/draft',
  'access_links': 'https://zenodo.org/api/records/18984935/access/links',
  'access_grants': 'https://zenodo.org/api/records/18984935/access/grants',
  'access_users': 'https://zenodo.org/api/records/18984935/access/users',
  'access_request': 'https://zenodo.org/api/records/18984935/access/request',
  'access': 'https://zenodo.org/api/records/18984935/access',
  'communities': 'https://zenodo.org/api/records/18984935/communities',
  'communities-suggestions': 'https://zenodo.org/api/records/18984935/communities-suggestions',
  'request_deletion': 'https://zenodo.org/api/records/18984935/request-deletion',
  'file_modification': 'https://zenodo.org/api/records/18984935/file-modification',
  'requests': 'https://zenodo.org/api/records/18984935/requests'},
 'updated': '2026-03-27T09:45:30.647460+00:00',
 'recid': '18984935',
 'revision': 3,
 'files': [{'id': 'cefc584d-56ba-41b2-8141-3a74069125bf',
   'key': '1250.pdf',
   'size': 458670,
   'checksum': 'md5:bdff934c03b593aebad643c7c107264a',
   'links': {'self': 'https://zenodo.org/api/records/18984935/files/1250.pdf/content'}},
  {'id': '6d9349d1-81c9-4709-88d4-ed40565041d7',
   'key': '1250_1.xlsx',
   'size': 554918,
   'checksum': 'md5:899d32de3f46de9cc4655f9958493b2b',
   'links': {'self': 'https://zenodo.org/api/records/18984935/files/1250_1.xlsx/content'}}],
 'swh': None,
 'owners': [{'id': '1455544'}],
 'status': 'published',
 'stats': {'downloads': 5,
  'unique_downloads': 2,
  'views': 4,
  'unique_views': 2,
  'version_downloads': 5,
  'version_unique_downloads': 2,
  'version_unique_views': 2,
  'version_views': 4},
 'state': 'done',
 'submitted': True}

df analysis

In [44]:
import pandas as pd

df = pd.read_json("./data/records.jsonl", lines=True)
df

,created,modified,id,conceptrecid,doi,conceptdoi,doi_url,metadata,title,links,updated,recid,revision,files,swh,owners,status,stats,state,submitted
0,1762334680954,2026-02-16 08:14:00.800,17530971,17530970,10.5281/zenodo.17530971,10.5281/zenodo.17530970,https://doi.org/10.5281/zenodo.17530971,{'title': 'L'état de l'Enseignement supérieur ...,L'état de l'Enseignement supérieur et de la Re...,{'self': 'https://zenodo.org/api/records/17530...,2026-02-16T08:14:00.800712+00:00,17530971,14,[{'id': 'beef22d7-4cfe-4137-960d-607740815b66'...,NaN,[{'id': '1451665'}],published,"{'downloads': 40, 'unique_downloads': 11, 'vie...",done,True
1,1762339497525,2026-02-16 08:15:31.286,17531403,17531402,10.5281/zenodo.17531403,10.5281/zenodo.17531402,https://doi.org/10.5281/zenodo.17531403,{'title': 'Les étudiants dans les écoles de ma...,Les étudiants dans les écoles de management re...,{'self': 'https://zenodo.org/api/records/17531...,2026-02-16T08:15:31.286240+00:00,17531403,21,[{'id': '827e6a53-dfaf-45e7-8d25-824de3ba45bf'...,NaN,[{'id': '1451665'}],published,"{'downloads': 30, 'unique_downloads': 14, 'vie...",done,True
2,1762339741994,2026-02-16 08:15:35.338,17531853,17531852,10.5281/zenodo.17531853,10.5281/zenodo.17531852,https://doi.org/10.5281/zenodo.17531853,{'title': 'Coût de l'Éducation en 2009 Évaluat...,Coût de l'Éducation en 2009 Évaluation proviso...,{'self': 'https://zenodo.org/api/records/17531...,2026-02-16T08:15:35.338313+00:00,17531853,7,[{'id': 'b093e083-908c-49b0-9469-5789658b8d59'...,NaN,[{'id': '1451665'}],published,"{'downloads': 17, 'unique_downloads': 13, 'vie...",done,True
3,1763048231588,2026-02-16 08:17:20.483,17601868,17601867,10.5281/zenodo.17601868,10.5281/zenodo.17601867,https://doi.org/10.5281/zenodo.17601868,{'title': 'Les étudiants inscrits dans les uni...,Les étudiants inscrits dans les universités pu...,{'self': 'https://zenodo.org/api/records/17601...,2026-02-16T08:17:20.483484+00:00,17601868,5,[{'id': '0ccbc3cb-76a7-4ab3-be8a-a2e7ba12fa62'...,NaN,[{'id': '1451665'}],published,"{'downloads': 4, 'unique_downloads': 4, 'views...",done,True
4,1763048364823,2026-02-16 08:17:25.241,17601893,17601892,10.5281/zenodo.17601893,10.5281/zenodo.17601892,https://doi.org/10.5281/zenodo.17601893,{'title': 'Le taux d'emploi salarié en France ...,Le taux d'emploi salarié en France des diplômé...,{'self': 'https://zenodo.org/api/records/17601...,2026-02-16T08:17:25.241966+00:00,17601893,5,[{'id': 'b277a26c-5132-4893-9f5b-fa9d536102cf'...,NaN,[{'id': '1451665'}],published,"{'downloads': 24, 'unique_downloads': 20, 'vie...",done,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906,1771248297863,2026-03-10 16:24:28.662,18660901,18660900,10.5281/zenodo.18660901,10.5281/zenodo.18660900,https://doi.org/10.5281/zenodo.18660901,{'title': 'Enseignement supérieur et recherche...,Enseignement supérieur et recherche : vers l'é...,{'self': 'https://zenodo.org/api/records/18660...,2026-03-10T16:24:28.662173+00:00,18660901,4,[{'id': '36986c98-dc07-4a76-b84f-a9b64dd85c72'...,NaN,[{'id': '1451665'}],published,"{'downloads': 1, 'unique_downloads': 1, 'views...",done,True
907,1773159984021,2026-03-10 16:32:37.377,18836560,18836559,10.5281/zenodo.18836560,10.5281/zenodo.18836559,https://doi.org/10.5281/zenodo.18836560,{'title': 'Vers l'égalité femmes-hommes ? Chif...,Vers l'égalité femmes-hommes ? Chiffres clés 2026,{'self': 'https://zenodo.org/api/records/18836...,2026-03-10T16:32:37.377669+00:00,18836560,4,[{'id': '2b4bbff5-05bf-4dd4-bd82-73e972b9b324'...,NaN,[{'id': '1455544'}],published,"{'downloads': 6, 'unique_downloads': 3, 'views...",done,True
908,1772092816575,2026-03-12 15:34:42.939,18758226,18758225,10.5281/zenodo.18758226,10.5281/zenodo.18758225,https://doi.org/10.5281/zenodo.18758226,{'title': 'Le Baromètre français de la Science...,Le Baromètre français de la Science Ouverte 2025,{'self': 'https://zenodo.org/api/records/18758...,2026-03-12T15:34:42.939724+00:00,18758226,6,[{'id': '79e12088-63f0-4dd0-9c1a-b5b935e49b6b'...,NaN,[{'id': '1455544'}],published,"{'downloads': 40, 'unique_downloads': 29, 'vie...",done,True
909,1774344779797,2026-03-24 09:33:00.302,18984755,18984754,10.5281/zenodo.18984755,10.5281/zenodo.18984754,https://doi.org/10.5281/zenodo.18984755,{'title': 'Le financement de la recherche et d...,Le financement de la recherche et de l'enseign...,{'self': 'https://zenodo.org/api/records/18984...,2026-03-24T09:33:00.302903+00:00,18984755,3,[{'id': '44763f9b-ccbc-481e-8aec-ddf1ac0b89a4'...,NaN,[{'id': '1455544'}],published,"{'downloads': 4, 'unique_downloads': 3, 'views...",done,True
910,1774604730042,2026-03-27 09:45:30.647,18984935,18984934,10.5281/zenodo.18984935,10.5281/zenodo.18984934,https://doi.org/10.5281/zenodo.18984935,{'title': 'L'activité de R&D selon les catégor...,L'activité de R&D selon les catégories d'entre...,{'self': 'https://zenodo.org/api/records/18984...,2026-03-27T09:45:30.647460+00:00,18984935,3,[{'id': 'cefc584d-56ba-41b2-8141-3a74069125bf'...,NaN,[{'id': '1455544'}],published,"{'downloads': 7, 'unique_downloads': 4, 'views...",done,True

In [134]:
resource_types = pd.json_normalize(df["metadata"])
resource_types

,title,doi,publication_date,description,access_right,creators,alternate_identifiers,communities,resource_type.title,resource_type.type,resource_type.subtype,imprint.place,imprint.isbn,license.id,relations.version,journal.issue,journal.title,keywords
0,L'état de l'Enseignement supérieur et de la Re...,10.5281/zenodo.17530971,2014-04-01,<strong>English:</strong><br>Higher Education ...,open,"[{'name': 'Belghith, Feres', 'affiliation': 'O...","[{'identifier': '1962-2546'}, {'identifier': '...",[{'id': 'ssm-esr'}],Book,publication,book,Etat de l'enseignement supérieur et de la rech...,978-2-11-099377-9,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",NaN,NaN,NaN
1,Les étudiants dans les écoles de management re...,10.5281/zenodo.17531403,2010-12-01,"<strong>English:</strong><br>In 2009-2010, 87,...",open,"[{'name': 'Gateaud, Gaëlle', 'affiliation': 'D...",[{'identifier': '2108-4033'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",10.10,Note d'information SIES,NaN
2,Coût de l'Éducation en 2009 Évaluation proviso...,10.5281/zenodo.17531853,2011-12-01,"<strong>Français:</strong><br>En 2009, la Fran...",open,"[{'name': 'Jeljoul, Martine', 'affiliation': '...",[{'identifier': '1286-9392'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",10.21,Note d'information DEPP,NaN
3,Les étudiants inscrits dans les universités pu...,10.5281/zenodo.17601868,2010-10-01,"<strong>English:</strong><br>In 2009-2010, the...",open,"[{'name': 'Papon, Sylvain', 'affiliation': 'Dé...",[{'identifier': '2108-4033'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",10.09,Note d'information SIES,NaN
4,Le taux d'emploi salarié en France des diplômé...,10.5281/zenodo.17601893,2024-12-19,<strong>Français:</strong><br>En 2023 45 000 é...,open,"[{'name': 'Aubry, Antonin', 'affiliation': 'So...",[{'identifier': '2729-1383'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",35,Note flash SIES,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906,Enseignement supérieur et recherche : vers l'é...,10.5281/zenodo.18660901,2025-03-07,<strong>Français:</strong><br>Cette 9e édition...,open,"[{'name': 'Aunay, Typhaine', 'affiliation': 'D...","[{'identifier': '2780-0954'}, {'identifier': '...",[{'id': 'ssm-esr'}],Book,publication,book,Vers l'égalité Femmes-Hommes ? Chiffres clés,978-2-11-179488-7,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",NaN,NaN,NaN
907,Vers l'égalité femmes-hommes ? Chiffres clés 2026,10.5281/zenodo.18836560,2026-03-06,<p>Cette dixi&egrave;me &eacute;dition pr&eacu...,open,"[{'name': 'Adedokun, Falilath', 'affiliation':...","[{'identifier': '2729-1502'}, {'identifier': '...",[{'id': 'ssm-esr'}],Book,publication,book,NaN,978-2-11-186061-2,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",NaN,NaN,NaN
908,Le Baromètre français de la Science Ouverte 2025,10.5281/zenodo.18758226,2026-02-26,<p>L&rsquo;&eacute;dition 2025 du Barom&egrave...,open,"[{'name': 'Jeangirard, Eric', 'affiliation': '...",[{'identifier': '2729-1383'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",04,Note flash SIES,NaN
909,Le financement de la recherche et de l'enseign...,10.5281/zenodo.18984755,2026-03-24,"<p>En 2024, les collectivit&eacute;s territori...",open,"[{'name': 'Béroud, Mallaury', 'affiliation': '...",[{'identifier': '2729-1383'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",NaN,NaN,NaN
910,L'activité de R&D selon les catégories d'entre...,10.5281/zenodo.18984935,2026-03-26,"<p>En 2023, les entreprises ont r&eacute;alis&...",open,"[{'name': 'Amoros, Pierre', 'affiliation': 'Mi...",[{'identifier': '2729-1383'}],[{'id': 'ssm-esr'}],Journal article,publication,article,NaN,NaN,cc-by-4.0,"[{'index': 0, 'is_last': True, 'parent': {'pid...",26.03,Note d'information SIES,NaN

In [136]:
resource_types["resource_type.subtype"].value_counts()

resource_type.subtype
article    842
book        69
Name: count, dtype: int64

In [54]:
df_exploded = df.explode(["files"], ignore_index=True)
df_norm = pd.json_normalize(df_exploded["files"])
df_files = pd.concat([df_exploded.drop(columns=["files"]).reset_index(drop=True), df_norm.reset_index(drop=True)], axis=1)
df_files

,created,modified,id,conceptrecid,doi,conceptdoi,doi_url,metadata,title,links,...,owners,status,stats,state,submitted,id,key,size,checksum,links.self
0,1762334680954,2026-02-16 08:14:00.800,17530971,17530970,10.5281/zenodo.17530971,10.5281/zenodo.17530970,https://doi.org/10.5281/zenodo.17530971,{'title': 'L'état de l'Enseignement supérieur ...,L'état de l'Enseignement supérieur et de la Re...,{'self': 'https://zenodo.org/api/records/17530...,...,[{'id': '1451665'}],published,"{'downloads': 40, 'unique_downloads': 11, 'vie...",done,True,beef22d7-4cfe-4137-960d-607740815b66,1.pdf,16961591,md5:fb3012daa8c6ac60dab49571a1af36f8,https://zenodo.org/api/records/17530971/files/...
1,1762339497525,2026-02-16 08:15:31.286,17531403,17531402,10.5281/zenodo.17531403,10.5281/zenodo.17531402,https://doi.org/10.5281/zenodo.17531403,{'title': 'Les étudiants dans les écoles de ma...,Les étudiants dans les écoles de management re...,{'self': 'https://zenodo.org/api/records/17531...,...,[{'id': '1451665'}],published,"{'downloads': 30, 'unique_downloads': 14, 'vie...",done,True,827e6a53-dfaf-45e7-8d25-824de3ba45bf,144.pdf,174312,md5:d6ae04fa8700a960fb0ec83d5b7b0132,https://zenodo.org/api/records/17531403/files/...
2,1762339741994,2026-02-16 08:15:35.338,17531853,17531852,10.5281/zenodo.17531853,10.5281/zenodo.17531852,https://doi.org/10.5281/zenodo.17531853,{'title': 'Coût de l'Éducation en 2009 Évaluat...,Coût de l'Éducation en 2009 Évaluation proviso...,{'self': 'https://zenodo.org/api/records/17531...,...,[{'id': '1451665'}],published,"{'downloads': 17, 'unique_downloads': 13, 'vie...",done,True,b093e083-908c-49b0-9469-5789658b8d59,145.pdf,97028,md5:d8d247dbbb51ed57d5cec4dfb5ec1740,https://zenodo.org/api/records/17531853/files/...
3,1763048231588,2026-02-16 08:17:20.483,17601868,17601867,10.5281/zenodo.17601868,10.5281/zenodo.17601867,https://doi.org/10.5281/zenodo.17601868,{'title': 'Les étudiants inscrits dans les uni...,Les étudiants inscrits dans les universités pu...,{'self': 'https://zenodo.org/api/records/17601...,...,[{'id': '1451665'}],published,"{'downloads': 4, 'unique_downloads': 4, 'views...",done,True,0ccbc3cb-76a7-4ab3-be8a-a2e7ba12fa62,146.pdf,107054,md5:e8bcaa4448a7cecb1c88bba6a7025795,https://zenodo.org/api/records/17601868/files/...
4,1763048364823,2026-02-16 08:17:25.241,17601893,17601892,10.5281/zenodo.17601893,10.5281/zenodo.17601892,https://doi.org/10.5281/zenodo.17601893,{'title': 'Le taux d'emploi salarié en France ...,Le taux d'emploi salarié en France des diplômé...,{'self': 'https://zenodo.org/api/records/17601...,...,[{'id': '1451665'}],published,"{'downloads': 24, 'unique_downloads': 20, 'vie...",done,True,b277a26c-5132-4893-9f5b-fa9d536102cf,1174.pdf,1088140,md5:b1f470a50439970bc142769603ace7ca,https://zenodo.org/api/records/17601893/files/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,1772092816575,2026-03-12 15:34:42.939,18758226,18758225,10.5281/zenodo.18758226,10.5281/zenodo.18758225,https://doi.org/10.5281/zenodo.18758226,{'title': 'Le Baromètre français de la Science...,Le Baromètre français de la Science Ouverte 2025,{'self': 'https://zenodo.org/api/records/18758...,...,[{'id': '1455544'}],published,"{'downloads': 40, 'unique_downloads': 29, 'vie...",done,True,41e59f0b-5f15-4e19-b4e0-70e033354a98,1247_1.xlsx,9580,md5:7045620b2ae648b06f709412c9a81a96,https://zenodo.org/api/records/18758226/files/...
1076,1774344779797,2026-03-24 09:33:00.302,18984755,18984754,10.5281/zenodo.18984755,10.5281/zenodo.18984754,https://doi.org/10.5281/zenodo.18984755,{'title': 'Le financement de la recherche et d...,Le financement de la recherche et de l'enseign...,{'self': 'https://zenodo.org/api/records/18984...,...,[{'id': '1455544'}],published,"{'downloads': 4, 'unique_downloads': 3, 'views...",done,True,44763f9b-ccbc-481e-8aec-ddf1ac0b89a4,1249_1.xlsx,897966,md5:1e032a654ae4ab748186f7855ca1546a,https://zenodo.org/api/records/18984755/files/...
1077,1774344779797,2026-03-24 09:33:00.302,18984755,18984754,10.5281/zenodo.18984755,10.5281/zenodo.18984754,https://doi.org/10.5281/zenodo.18984755,{'title': 'Le financement de la recherche et d...,Le financement de la recherche et de l'enseign...,{'self': 'https://zenodo.org/api/records/18984...,...,[{'id': '1455544'}],published,"{'downloads': 4, 'unique_downloads': 3, 'views...",done,True,1fd63c8c-5a65-47ae-9147-93e00b6af6df,1249.pdf,1093925,md5:4757cd70dc57c2077d5add4fe0f0a554,https://zenodo.org/api/records/18984755/files/...
1078,1774604730042,2026-03-27 09:45:30.647,18984935,18984934,10.5281/zenodo.18984935,10.5281/zenodo.18984934,https://doi.org/10.5281/zenodo.18984935,{'title': 'L'activité de R&D selon les catégor...,L'activité de R&D selon les catégories d'entre...,{'self': 'https://zenodo.org/api/records/18984...,...,[{'id': '1455544'}],published,"{'downloads': 7, 'unique_downloads': 4, 'views...",done,True,cefc584d-56ba-41b2-8141-3a74069125bf,1250.pdf,458670,md5:bdff934c03b593aebad643c7c107264a,https://zenodo.org/api/records/18984935/files/...
1079,1774604730042,2026-03-27 09:45:30.647,18984935,18984934,10.5281/zenodo.18984935,10.5281/zenodo.18984934,https://doi.org/10.5281/zenodo.18984935,{'title': 'L'activité de R&D selon les catégor...,L'activité de R&D selon les catégories d'entre...,{'self': 'https://zenodo.org/api/records/18984...,...,[{'id': '1455544'}],published,"{'downloads': 7, 'unique_downloads': 4, 'views...",done,True,6d9349d1-81c9-4709-88d4-ed40565041d7,1250_1.xlsx,554918,md5:899d32de3f46de9cc4655f9958493b2b,https://zenodo.org/api/records/18984935/files/...

In [133]:
df.head(2).to_dict()

{'created': {0: 1762334680954, 1: 1762339497525},
 'modified': {0: Timestamp('2026-02-16 08:14:00.800000'),
  1: Timestamp('2026-02-16 08:15:31.286000')},
 'id': {0: 17530971, 1: 17531403},
 'conceptrecid': {0: 17530970, 1: 17531402},
 'doi': {0: '10.5281/zenodo.17530971', 1: '10.5281/zenodo.17531403'},
 'conceptdoi': {0: '10.5281/zenodo.17530970', 1: '10.5281/zenodo.17531402'},
 'doi_url': {0: 'https://doi.org/10.5281/zenodo.17530971',
  1: 'https://doi.org/10.5281/zenodo.17531403'},
 'metadata': {0: {'title': "L'état de l'Enseignement supérieur et de la Recherche en France n°7",
   'doi': '10.5281/zenodo.17530971',
   'publication_date': '2014-04-01',
   'description': "<strong>English:</strong><br>Higher Education and Research, Facts and Figures presents an annual overview, backed up by figures, of developments within the French system, its resources and outcomes. Wherever the data permit, an international comparison is provided. A double page is devoted to each of the 47 themes, including a summary of the latest available data along with graphs, tables and comments.<br><br><strong>Français:</strong><br>L'état de l'Enseignement supérieur et de la Recherche constitue un état des lieux annuel et chiffré du système français, de ses évolutions, des moyens qu'il met en œuvre et de ses résultats, en le situant, chaque fois que les données le permettent, au niveau international. Chacune des 47 fiches présente sur une double page, au moyen de graphiques, de tableaux et de commentaires, les dernières données de synthèse disponibles sur chaque sujet.",
   'access_right': 'open',
   'creators': [{'name': 'Belghith, Feres',
     'affiliation': 'Observatoire de la Vie Étudiante'},
    {'name': 'Bideault, Marc',
     'affiliation': "Département des études d'effectifs et d'analyse des ressources humaines"},
    {'name': 'Bretagnolle, Annie',
     'affiliation': "Sous-direction de l'égalité des chances et de la vie étudiante"},
    {'name': 'Calmand, Julien',
     'affiliation': 'Département entrées et évolutions dans la vie active',
     'orcid': '0000-0003-1688-3218'},
    {'name': 'Dalous, Jean-Pierre',
     'affiliation': "Bureau du compte de l'éducation et du patrimoine des établissements"},
    {'name': 'Dauphin, Laurence',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'David, Catherine',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Demongeot, Aurélie',
     'affiliation': "Bureau des études statistiques sur la formation des adultes, l'apprentissage et l'insertion des jeunes"},
    {'name': 'Dixte, Christophe',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Filliatreau, Ghislaine',
     'affiliation': 'Observatoire des Sciences et des Techniques',
     'orcid': '0000-0001-8789-1704'},
    {'name': 'Fouquet, Samuel',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'Ganem, Patricia',
     'affiliation': "Bureau du compte de l'éducation et du patrimoine des établissements"},
    {'name': 'Grille, Joëlle',
     'affiliation': "Bureau des études statistiques sur la formation des adultes, l'apprentissage et l'insertion des jeunes"},
    {'name': 'Jaggers, Christophe',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'Jeljoul, Martine',
     'affiliation': "Bureau du compte de l'éducation et du patrimoine des établissements"},
    {'name': 'Le Corgne, Simon',
     'affiliation': 'Observatoire de la Vie Étudiante'},
    {'name': 'Le Rhun, Béatrice',
     'affiliation': "Bureau des études statistiques sur la formation des adultes, l'apprentissage et l'insertion des jeunes"},
    {'name': 'Liogier, Valérie',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'Maetz, Isabelle',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'Montenache, Stéphane',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Nisslé, Claudette-Vincent',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Perrain, Laurent',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Poulet-Coulibando, Pascale',
     'affiliation': "Bureau des études statistiques sur la formation des adultes, l'apprentissage et l'insertion des jeunes"},
    {'name': 'Quemener, Justin',
     'affiliation': "Département des politiques d'incitation à la recherche et développement",
     'orcid': '0009-0004-2656-5680'},
    {'name': 'Prouteau, Danielle',
     'affiliation': 'Bureau des études statistiques sur les personnels'},
    {'name': 'Robert-Bobée, Isabelle',
     'affiliation': "Bureau des études statistiques sur la formation des adultes, l'apprentissage et l'insertion des jeunes"},
    {'name': 'Rudolf, Marguerite',
     'affiliation': "Bureau du compte de l'éducation et du patrimoine des établissements"},
    {'name': 'Roth, Chris',
     'affiliation': 'Observatoire des Sciences et des Techniques'},
    {'name': 'Péan, Sylvaine',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"},
    {'name': 'Thomas, Fanny',
     'affiliation': 'Bureau des études statistiques sur les élèves'},
    {'name': 'Testas, Anna',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Wolber, Odile',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Weisenburger, Emmanuel',
     'affiliation': 'Département ingénierie et science des données',
     'orcid': '0000-0002-9752-8834'},
    {'name': 'Ramanana-Rahary, Suzy',
     'affiliation': 'Observatoire des Sciences et des Techniques'},
    {'name': 'Laville, Françoise',
     'affiliation': 'Observatoire des Sciences et des Techniques'},
    {'name': 'Robert, Catherine',
     'affiliation': 'Observatoire des Sciences et des Techniques'},
    {'name': 'Sachwald, Frédérique',
     'affiliation': "Service de l'innovation, du transfert de technologie et de l'action régionale"},
    {'name': 'Taillibert, Marie-Laure',
     'affiliation': 'Observatoire des Sciences et des Techniques'},
    {'name': 'Ferro, Mathilde',
     'affiliation': 'Observatoire de la Vie Étudiante'},
    {'name': 'Boinet, Alexis',
     'affiliation': 'Département des études statistiques de la recherche'},
    {'name': 'Roussel, Philippe',
     'affiliation': 'Département des études statistiques de la recherche'}],
   'resource_type': {'title': 'Book',
    'type': 'publication',
    'subtype': 'book'},
   'imprint': {'place': "Etat de l'enseignement supérieur et de la recherche",
    'isbn': '978-2-11-099377-9'},
   'alternate_identifiers': [{'identifier': '1962-2546'},
    {'identifier': '978-2-11-099377-9'}],
   'license': {'id': 'cc-by-4.0'},
   'communities': [{'id': 'ssm-esr'}],
   'relations': {'version': [{'index': 0,
      'is_last': True,
      'parent': {'pid_type': 'recid', 'pid_value': '17530970'}}]}},
  1: {'title': 'Les étudiants dans les écoles de management reconnues à diplôme visé en 2009-2010',
   'doi': '10.5281/zenodo.17531403',
   'publication_date': '2010-12-01',
   'description': "<strong>English:</strong><br>In 2009-2010, 87,800 students were following courses in one of the 84 recognised business schools authorised to award approved diplomas. This was an increase of 18.6% against the start of the 2008-09 academic year. Newly enrolled students had either just passed their baccalauréat and were going to schools that recruited baccalauréat holders, or they came from classes preparing for admission to the Grandes Ecoles (¦Classe préparatoire aux grandes écoles - ¦CPGE), from universities, from Advanced technician's sections (¦Section de technicien supérieur - ¦STS) or from Technological university institutes (Institut universitaire de technologie - IUT) and were entering schools that recruited students with the baccalauréat + 2 years of study. Men outnumbered women slightly, but the proportion of women was increasing steadily. More and more foreign students were following courses in business and management schools. As with women students, there were fewer foreign students in the first cycle programmes and a greater proportion in the Master of Business Administration (MBA) courses.<br><br><strong>Français:</strong><br>En 2009-2010, 87 800 étudiants suivent une formation dans l'une des 84 écoles de management reconnues et habilitées à délivrer un diplôme visé, soit une hausse de 18,6 % par rapport à la rentrée 2008. Les nouveaux inscrits viennent soit d'obtenir le baccalauréat et se dirigent vers les écoles recrutant au niveau baccalauréat ; soit de classes préparatoires aux grandes écoles, de l'université, de STS ou d'IUT et s'orientent vers les écoles recrutant au niveau bac + 2. Les hommes sont légèrement majoritaires,mais la proportion de femmes ne cesse d'augmenter. Les étudiants étrangers sont de plus en plus nombreux à suivre un cursus dans une école de commerce et de gestion.Commeles étudiantes, les étrangers sont moins présents dans le cycle de formation principale et davantage représentés dans le master of business administration (MBA).",
   'access_right': 'open',
   'creators': [{'name': 'Gateaud, Gaëlle',
     'affiliation': "Département des études statistiques de l'enseignement supérieur"}],
   'resource_type': {'title': 'Journal article',
    'type': 'publication',
    'subtype': 'article'},
   'journal': {'issue': '10.10', 'title': "Note d'information SIES"},
   'alternate_identifiers': [{'identifier': '2108-4033'}],
   'license': {'id': 'cc-by-4.0'},
   'communities': [{'id': 'ssm-esr'}],
   'relations': {'version': [{'index': 0,
      'is_last': True,
      'parent': {'pid_type': 'recid', 'pid_value': '17531402'}}]}}},
 'title': {0: "L'état de l'Enseignement supérieur et de la Recherche en France n°7",
  1: 'Les étudiants dans les écoles de management reconnues à diplôme visé en 2009-2010'},
 'links': {0: {'self': 'https://zenodo.org/api/records/17530971',
   'self_html': 'https://zenodo.org/records/17530971',
   'preview_html': 'https://zenodo.org/records/17530971?preview=1',
   'doi': 'https://doi.org/10.5281/zenodo.17530971',
   'self_doi': 'https://doi.org/10.5281/zenodo.17530971',
   'self_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.17530971',
   'reserve_doi': 'https://zenodo.org/api/records/17530971/draft/pids/doi',
   'parent': 'https://zenodo.org/api/records/17530970',
   'parent_html': 'https://zenodo.org/records/17530970',
   'parent_doi': 'https://doi.org/10.5281/zenodo.17530970',
   'parent_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.17530970',
   'self_iiif_manifest': 'https://zenodo.org/api/iiif/record:17530971/manifest',
   'self_iiif_sequence': 'https://zenodo.org/api/iiif/record:17530971/sequence/default',
   'files': 'https://zenodo.org/api/records/17530971/files',
   'media_files': 'https://zenodo.org/api/records/17530971/media-files',
   'thumbnails': {'10': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E10,/0/default.jpg',
    '50': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E50,/0/default.jpg',
    '100': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E100,/0/default.jpg',
    '250': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E250,/0/default.jpg',
    '750': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E750,/0/default.jpg',
    '1200': 'https://zenodo.org/api/iiif/record:17530971:1.pdf/full/%5E1200,/0/default.jpg'},
   'archive': 'https://zenodo.org/api/records/17530971/files-archive',
   'archive_media': 'https://zenodo.org/api/records/17530971/media-files-archive',
   'latest': 'https://zenodo.org/api/records/17530971/versions/latest',
   'latest_html': 'https://zenodo.org/records/17530971/latest',
   'versions': 'https://zenodo.org/api/records/17530971/versions',
   'draft': 'https://zenodo.org/api/records/17530971/draft',
   'access_links': 'https://zenodo.org/api/records/17530971/access/links',
   'access_grants': 'https://zenodo.org/api/records/17530971/access/grants',
   'access_users': 'https://zenodo.org/api/records/17530971/access/users',
   'access_request': 'https://zenodo.org/api/records/17530971/access/request',
   'access': 'https://zenodo.org/api/records/17530971/access',
   'communities': 'https://zenodo.org/api/records/17530971/communities',
   'communities-suggestions': 'https://zenodo.org/api/records/17530971/communities-suggestions',
   'request_deletion': 'https://zenodo.org/api/records/17530971/request-deletion',
   'file_modification': 'https://zenodo.org/api/records/17530971/file-modification',
   'requests': 'https://zenodo.org/api/records/17530971/requests'},
  1: {'self': 'https://zenodo.org/api/records/17531403',
   'self_html': 'https://zenodo.org/records/17531403',
   'preview_html': 'https://zenodo.org/records/17531403?preview=1',
   'doi': 'https://doi.org/10.5281/zenodo.17531403',
   'self_doi': 'https://doi.org/10.5281/zenodo.17531403',
   'self_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.17531403',
   'reserve_doi': 'https://zenodo.org/api/records/17531403/draft/pids/doi',
   'parent': 'https://zenodo.org/api/records/17531402',
   'parent_html': 'https://zenodo.org/records/17531402',
   'parent_doi': 'https://doi.org/10.5281/zenodo.17531402',
   'parent_doi_html': 'https://zenodo.org/doi/10.5281/zenodo.17531402',
   'self_iiif_manifest': 'https://zenodo.org/api/iiif/record:17531403/manifest',
   'self_iiif_sequence': 'https://zenodo.org/api/iiif/record:17531403/sequence/default',
   'files': 'https://zenodo.org/api/records/17531403/files',
   'media_files': 'https://zenodo.org/api/records/17531403/media-files',
   'thumbnails': {'10': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E10,/0/default.jpg',
    '50': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E50,/0/default.jpg',
    '100': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E100,/0/default.jpg',
    '250': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E250,/0/default.jpg',
    '750': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E750,/0/default.jpg',
    '1200': 'https://zenodo.org/api/iiif/record:17531403:144.pdf/full/%5E1200,/0/default.jpg'},
   'archive': 'https://zenodo.org/api/records/17531403/files-archive',
   'archive_media': 'https://zenodo.org/api/records/17531403/media-files-archive',
   'latest': 'https://zenodo.org/api/records/17531403/versions/latest',
   'latest_html': 'https://zenodo.org/records/17531403/latest',
   'versions': 'https://zenodo.org/api/records/17531403/versions',
   'draft': 'https://zenodo.org/api/records/17531403/draft',
   'access_links': 'https://zenodo.org/api/records/17531403/access/links',
   'access_grants': 'https://zenodo.org/api/records/17531403/access/grants',
   'access_users': 'https://zenodo.org/api/records/17531403/access/users',
   'access_request': 'https://zenodo.org/api/records/17531403/access/request',
   'access': 'https://zenodo.org/api/records/17531403/access',
   'communities': 'https://zenodo.org/api/records/17531403/communities',
   'communities-suggestions': 'https://zenodo.org/api/records/17531403/communities-suggestions',
   'request_deletion': 'https://zenodo.org/api/records/17531403/request-deletion',
   'file_modification': 'https://zenodo.org/api/records/17531403/file-modification',
   'requests': 'https://zenodo.org/api/records/17531403/requests'}},
 'updated': {0: '2026-02-16T08:14:00.800712+00:00',
  1: '2026-02-16T08:15:31.286240+00:00'},
 'recid': {0: 17530971, 1: 17531403},
 'revision': {0: 14, 1: 21},
 'files': {0: [{'id': 'beef22d7-4cfe-4137-960d-607740815b66',
    'key': '1.pdf',
    'size': 16961591,
    'checksum': 'md5:fb3012daa8c6ac60dab49571a1af36f8',
    'links': {'self': 'https://zenodo.org/api/records/17530971/files/1.pdf/content'}}],
  1: [{'id': '827e6a53-dfaf-45e7-8d25-824de3ba45bf',
    'key': '144.pdf',
    'size': 174312,
    'checksum': 'md5:d6ae04fa8700a960fb0ec83d5b7b0132',
    'links': {'self': 'https://zenodo.org/api/records/17531403/files/144.pdf/content'}}]},
 'swh': {0: nan, 1: nan},
 'owners': {0: [{'id': '1451665'}], 1: [{'id': '1451665'}]},
 'status': {0: 'published', 1: 'published'},
 'stats': {0: {'downloads': 40,
   'unique_downloads': 11,
   'views': 25,
   'unique_views': 12,
   'version_downloads': 40,
   'version_unique_downloads': 11,
   'version_unique_views': 12,
   'version_views': 25},
  1: {'downloads': 30,
   'unique_downloads': 14,
   'views': 25,
   'unique_views': 16,
   'version_downloads': 30,
   'version_unique_downloads': 14,
   'version_unique_views': 16,
   'version_views': 25}},
 'state': {0: 'done', 1: 'done'},
 'submitted': {0: True, 1: True}}

In [130]:
df[df["id"] == "17530971"]

Empty DataFrame
Columns: [created, modified, id, conceptrecid, doi, conceptdoi, doi_url, metadata, title, links, updated, recid, revision, files, swh, owners, status, stats, state, submitted]
Index: []

In [129]:
df_files[df_files["key"] == "1.pdf"]

,created,modified,id,conceptrecid,doi,conceptdoi,doi_url,metadata,title,links,...,owners,status,stats,state,submitted,id,key,size,checksum,links.self
0,1762334680954,2026-02-16 08:14:00.800,17530971,17530970,10.5281/zenodo.17530971,10.5281/zenodo.17530970,https://doi.org/10.5281/zenodo.17530971,{'title': 'L'état de l'Enseignement supérieur ...,L'état de l'Enseignement supérieur et de la Re...,{'self': 'https://zenodo.org/api/records/17530...,...,[{'id': '1451665'}],published,"{'downloads': 40, 'unique_downloads': 11, 'vie...",done,True,beef22d7-4cfe-4137-960d-607740815b66,1.pdf,16961591,md5:fb3012daa8c6ac60dab49571a1af36f8,https://zenodo.org/api/records/17530971/files/...

In [ ]:
df_dup = df_files[df_files.duplicated(subset="key")]
df_dup[["modified", "id", "doi", "key", "checksum", "links.self"]]

,modified,id,id,doi,key,checksum,links.self
635,2026-02-16 13:14:03.909,18660447,acde2b8e-44c4-4f96-b8fb-d8d0d76b83fa,10.5281/zenodo.18660447,1003.pdf,md5:eb163b7581d04e65c8830c65ca30446d,https://zenodo.org/api/records/18660447/files/...
636,2026-02-16 13:14:07.087,18660449,c7716cf2-866d-49d4-9ee3-224b41510ab9,10.5281/zenodo.18660449,1003.pdf,md5:eb163b7581d04e65c8830c65ca30446d,https://zenodo.org/api/records/18660449/files/...
637,2026-02-16 13:14:10.575,18660451,e5f23458-d3ce-417a-a182-4a7234bd8024,10.5281/zenodo.18660451,1003.pdf,md5:eb163b7581d04e65c8830c65ca30446d,https://zenodo.org/api/records/18660451/files/...
638,2026-02-16 13:14:14.617,18660455,e0c72284-f345-44d5-9195-e3b967406f28,10.5281/zenodo.18660455,1003.pdf,md5:eb163b7581d04e65c8830c65ca30446d,https://zenodo.org/api/records/18660455/files/...
939,2026-02-16 16:44:24.467,18662899,a1561402-b919-4b1f-a7d8-d7242d453b2a,10.5281/zenodo.18662899,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662899/files/...
940,2026-02-16 16:44:27.586,18662901,29fe0bff-0e81-4f91-9b02-faa21dd71b74,10.5281/zenodo.18662901,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662901/files/...
941,2026-02-16 16:44:30.954,18662903,4627018c-fb1d-4b7f-82bb-3b8d3d882592,10.5281/zenodo.18662903,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662903/files/...
942,2026-02-16 16:44:34.118,18662905,bcc3100a-d5f1-4d8b-8a31-989138c3683e,10.5281/zenodo.18662905,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662905/files/...
943,2026-02-16 16:44:38.721,18662907,68cdafc7-d20a-4a7d-bf6d-b8411c4ee25e,10.5281/zenodo.18662907,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662907/files/...
944,2026-02-16 16:44:41.373,18662909,c029e7e2-c30b-4f79-9a70-6234ceac013d,10.5281/zenodo.18662909,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662909/files/...
945,2026-02-16 16:44:44.135,18662911,240cdc43-bf87-4fec-acb8-42bacd3d2c9b,10.5281/zenodo.18662911,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662911/files/...
946,2026-02-16 16:44:46.303,18662913,35b95df8-81a4-4e59-acae-5ba8a130ce71,10.5281/zenodo.18662913,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662913/files/...
947,2026-02-16 16:44:49.193,18662919,077b3809-ffed-437c-b2be-40c9def19f1c,10.5281/zenodo.18662919,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662919/files/...
948,2026-02-16 16:44:52.236,18662923,22760044-f884-42ac-8b98-cc875d706cd4,10.5281/zenodo.18662923,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662923/files/...
949,2026-02-16 16:44:54.753,18662925,7b42d874-cb0e-4374-9d4a-6f0fa7883778,10.5281/zenodo.18662925,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662925/files/...
950,2026-02-16 16:45:03.142,18662933,0e712a69-f65d-453e-9125-8673ece515ff,10.5281/zenodo.18662933,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662933/files/...
951,2026-02-16 16:45:06.328,18662937,baee9d49-2366-4ead-8071-26124a116ca5,10.5281/zenodo.18662937,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662937/files/...
952,2026-02-16 16:45:25.992,18662951,9cfb2730-f1fc-4a06-9b5e-91e1c822965b,10.5281/zenodo.18662951,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662951/files/...
1026,2026-02-19 08:21:39.580,18662931,7a6c9253-e9d5-456d-b995-8fba84cfaf8b,10.5281/zenodo.18662931,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662931/files/...
1031,2026-02-19 08:24:25.077,18662927,2fba8e2a-057f-4866-91c1-60ce47d7646f,10.5281/zenodo.18662927,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18662927/files/...
1048,2026-02-19 11:05:31.652,18659005,e7dad2ea-0131-41e6-b97f-2607d1a46c7f,10.5281/zenodo.18659005,empty_file.txt,md5:a4238077e640c040a159a716150466e6,https://zenodo.org/api/records/18659005/files/...

In [66]:
df_files[df_files["key"] == "1003.pdf"][["doi", "doi_url", "title", "links.self", "modified"]].to_dict(orient="records")

[{'doi': '10.5281/zenodo.18660443',
  'doi_url': 'https://doi.org/10.5281/zenodo.18660443',
  'title': 'Les boursiers sur critères sociaux en 2020-2021',
  'links.self': 'https://zenodo.org/api/records/18660443/files/1003.pdf/content',
  'modified': Timestamp('2026-02-16 13:14:00.075000')},
 {'doi': '10.5281/zenodo.18660447',
  'doi_url': 'https://doi.org/10.5281/zenodo.18660447',
  'title': 'Les boursiers sur critères sociaux en 2020-2021',
  'links.self': 'https://zenodo.org/api/records/18660447/files/1003.pdf/content',
  'modified': Timestamp('2026-02-16 13:14:03.909000')},
 {'doi': '10.5281/zenodo.18660449',
  'doi_url': 'https://doi.org/10.5281/zenodo.18660449',
  'title': 'Les boursiers sur critères sociaux en 2020-2021',
  'links.self': 'https://zenodo.org/api/records/18660449/files/1003.pdf/content',
  'modified': Timestamp('2026-02-16 13:14:07.087000')},
 {'doi': '10.5281/zenodo.18660451',
  'doi_url': 'https://doi.org/10.5281/zenodo.18660451',
  'title': 'Les boursiers sur critères sociaux en 2020-2021',
  'links.self': 'https://zenodo.org/api/records/18660451/files/1003.pdf/content',
  'modified': Timestamp('2026-02-16 13:14:10.575000')},
 {'doi': '10.5281/zenodo.18660455',
  'doi_url': 'https://doi.org/10.5281/zenodo.18660455',
  'title': 'Les boursiers sur critères sociaux en 2020-2021',
  'links.self': 'https://zenodo.org/api/records/18660455/files/1003.pdf/content',
  'modified': Timestamp('2026-02-16 13:14:14.617000')}]

pdf extraction

In [128]:
import os
from mistralai.client import Mistral
from dotenv import load_dotenv

load_dotenv()

client = Mistral(api_key=os.getenv("MISTRAL_API_KEY"))

In [78]:
import base64


def encode_pdf(pdf_path):
    try:
        with open(pdf_path, "rb") as pdf_file:
            return base64.b64encode(pdf_file.read()).decode("utf-8")
    except Exception as error:
        print(f"Error: {error}")
        return None

In [98]:
import json

pdf_path = "./data/pdf/1003.pdf"
base64_pdf = encode_pdf(pdf_path)

response = client.ocr.process(
    model="mistral-ocr-latest",
    document={
        "type": "document_url",
        "document_url": f"data:application/pdf;base64,{base64_pdf}",
        "document_name": "1003.pdf",
    },
    extract_footer=True,
    extract_header=True,
)
data = json.loads(response.model_dump_json())

In [127]:
response.model_dump_json()

'{"pages":[{"index":0,"markdown":"# Les boursiers sur critères sociaux en 2020-2021\\n\\nDurant l\'année universitaire 2020-2021, marquée par la crise sanitaire, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du M.E.S.R.I., soit une hausse de plus de 4 % en 1 an. Cette hausse atteint 7 % pour les étudiants ayant les plus faibles ressources. La proportion de boursiers au sein des formations ouvrant droit aux bourses dépasse 38 %, taux en hausse annuelle de 1,6 point après 4 années de baisse. De nouvelles aides à destination des boursiers ont été créées au cours de l\'année pour faire face au prolongement de la crise. Entre septembre 2020 et juin 2021, plus de 315 000 étudiants boursiers ont bénéficié de l\'une d\'elles : le ticket repas à 1 euro. Cette aide a été pérennisée comme un droit connexe aux BCS en juillet 2021.\\n\\n## En 2020-2021, 750 000 étudiants boursiers\\n\\nDurant l\'année universitaire 2020-2021, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du ministère de l\'enseignement supérieur, de la recherche et de l\'innovation¹ (M.E.S.R.I.). Ces bourses ne peuvent être attribuées qu\'aux étudiants inscrits dans une formation habilitée par le ministère en charge de l\'enseignement supérieur à recevoir des boursiers, avec des conditions sur l\'âge, le régime d\'inscription, la nationalité et le diplôme.\\n\\nElles sont accordées en fonction des ressources et des charges de la famille appréciées selon un barème national qui détermine le montant annuel de la bourse. L\'échelon 7, échelon pour les ressources les plus faibles, correspond à une bourse de 5 679 € annuels et concerne 7,5 % des boursiers. Près d\'un tiers des boursiers ont une bourse supérieure à 4 610 €, ce montant est supérieur à 2 571 € pour plus de la moitié des boursiers. Enfin, 32 % des boursiers sont à l\'échelon 0 et bénéficient d\'une aide de 1 032 €.\\n\\n### Effectifs de boursiers sur critères sociaux\\n\\n|   | Montant annuel en euros * | Effectifs | % | % de femmes  |\\n| --- | --- | --- | --- | --- |\\n|  Echelon 0 | 1 032 | 238 162 | 31,8 | 56,8  |\\n|  Echelon 1 | 1 707 | 105 137 | 14,0 | 57,6  |\\n|  Echelon 2 | 2 571 | 55 004 | 7,3 | 58,1  |\\n|  Echelon 3 | 3 292 | 55 578 | 7,4 | 58,8  |\\n|  Echelon 4 | 4 015 | 53 554 | 7,1 | 58,7  |\\n|  Echelon 5 | 4 610 | 97 850 | 13,1 | 59,3  |\\n|  Echelon 6 | 4 889 | 88 185 | 11,8 | 59,8  |\\n|  Echelon 7 | 5 679 | 56 092 | 7,5 | 61,0  |\\n|  |   |   |   |   |\\n|  Total |  | 749 562 | 100 | 58,3  |\\n|  Aide au mérite | 900 | 45 353 | 6,1 | 64,1  |\\n\\n* Les montants des BCS ne prennent pas en compte le supplément de 150 euros versé aux boursiers en décembre 2020 en raison de la crise sanitaire.\\nSource : MESRI-SIES / Système d\'information AGLAE, extraction 15/03/2021\\n\\nPour les bacheliers bénéficiant d\'une BCS et ayant eu une mention « Très bien », une aide au mérite vient compléter la BCS durant trois ans. En 2020, cette aide était de 900 €.\\n\\n## 38,4 % de boursiers, en hausse de 1,6 point\\n\\nLe nombre de boursiers a augmenté de plus de 4,4 % en un an, une hausse deux fois plus importante que celle des inscriptions à la rentrée 2020². Cette augmentation atteint 6,9 % au sein des échelons 5, 6 et 7 qui concernent les étudiants ayant les ressources les plus faibles. La part des étudiants boursiers dans les formations ouvrant droit à une bourse du M.E.S.R.I. est de 38,4 % en 2020-2021. En baisse depuis 4 ans, ce taux augmente fortement cette année (+1,6 point), dépassant la part de boursiers observée à la rentrée 2015 (37,9 %).\\n\\nDes disparités par académie et par genre persistent. La part de boursiers est très élevée en Outre-mer (de 46 à 63 %). Par contraste, environ un tiers des étudiants des académies de Strasbourg et Lyon sont boursiers, et seulement d\'un peu plus d\'un quart dans les académies de Paris et Versailles. La part de boursiers dans une académie dépend non seulement du niveau de vie des familles mais aussi de l\'offre de formation.\\n\\nParmi l\'ensemble des étudiantes, quatre sur dix sont boursières. C\'est le cas d\'un étudiant sur trois. Cet écart s\'explique par une plus forte propension des femmes à poursuivre des études dans les milieux les plus modestes. Elles sont d\'ailleurs plus nombreuses parmi les échelons les plus élevés où elles représentent 60 % des boursiers contre 57 % à l\'échelon 0. Des disparités se retrouvent aussi selon les formations : on observe davantage de boursières que de boursiers en STS (+5 points) et en IUT (+4 points) ; l\'écart est moindre en CPGE, dans les écoles d\'ingénieur ou de commerce qui accueillent moins d\'étudiants boursiers.\\n\\n1 Les étudiants peuvent bénéficier d\'autres aides, non prises en compte ici : aides spécifiques ponctuelles du MESRI, bourses d\'établissement et des autres ministères. Les aides spécifiques ponctuelles (ASP), ouvertes aux étudiants boursiers ou non, varient fortement selon la conjoncture. En lien avec la crise sanitaire, de septembre 2020 à avril 2021, le nombre de bénéficiaires par mois était, en moyenne, de 43 % plus élevé que l\'année précédente. Le montant des aides allouées a progressé de 57 % sur la même période.\\n2 Entre les rentrées 2019 et 2020, le nombre des inscriptions dans l\'ensemble de l\'enseignement supérieur a progressé de 2,1 % (formations non éligibles aux BCS du MESRI comprises)","images":[],"dimensions":{"dpi":200,"height":2338,"width":1653},"tables":[],"hyperlinks":[],"header":"MINISTÈRE\\nDE L\'ENSEIGNEMENT\\nSUPÉRIEUR,\\nDE LA RECHERCHE\\nET DE L\'INNOVATION\\n\\nLiberté\\nÉgalité\\nFraternité\\n\\nNOTE FLASH DU\\nSIES\\nEnseignement supérieur, Recherche, Innovation\\nN° 20\\nSeptembre 2021","footer":"Note Flash n°20 – septembre 2021"},{"index":1,"markdown":"# Plus de la moitié des étudiants en STS sont boursiers\\n\\nSelon la filière et le type d\'établissement, la proportion de boursiers sur critères sociaux est très variable. Plus de la moitié des étudiants dans les sections de technicien supérieur et assimilés (STS) sont boursiers (55 %) et moins de trois sur dix en classes préparatoires aux grandes écoles (CPGE). La part des boursiers des formations d\'ingénieurs diffère selon qu\'elles soient universitaires (34 %) ou non (23 %). Les écoles de commerce sont les formations accueillant le moins d\'étudiants boursiers (12 %).\\n\\n## Boursiers sur critères sociaux selon la formation suivie\\n\\n|   | % de boursiers | Effectifs | % de boursières parmi les étudiants  |\\n| --- | --- | --- | --- |\\n|  Université | 41,0 | 532 594 | 43,1  |\\n|  dont : Préparation DUT | 45,2 | 49 579 | 49,0  |\\n|  Filières ingénieurs | 34,0 | 8 373 | 32,4  |\\n|  Univ. hors DUT et Ingé. | 40,8 | 474 642 | 42,8  |\\n|  CPGE | 27,3 | 22 435 | 27,8  |\\n|  dont : secteur public | 29,1 | 20 114 | 29,5  |\\n|  secteur privé | 17,9 | 2 321 | 17,5  |\\n|  STS et assimilées | 54,9 | 119 934 | 60,1  |\\n|  dont : secteur public | 58,1 | 94 796 | 64,0  |\\n|  secteur privé | 45,5 | 25 138 | 49,8  |\\n|  Form. d\'ingénieurs hors univ. | 22,8 | 20 231 | 23,2  |\\n|  Écoles de commerce | 12,4 | 17 476 | 13,2  |\\n|  Grands étab. de type univ. | 23,3 | 6 263 | 25,7  |\\n|  Étab. d\'enseignement univ. privés | 27,4 | 8 918 | 28,7  |\\n|  Autres écoles | 27,1 | 17 565 | 33,2  |\\n|  Scolarité à l\'étranger (1) | - | 4 146 | -  |\\n|  Total bourses | 38,4 | 749 562 | 41,0  |\\n|  dont : secteur public | 41,2 | 675 340 | 43,5  |\\n|  secteur privé | 22,4 | 70 076 | 25,4  |\\n\\n(1) : Il s\'agit d\'étudiants qui perçoivent une BCS en étant inscrit dans un établissement d\'enseignement supérieur étranger\\nSource : MESRI-SIES / Système d\'information AGLAE, extraction 15/03/2021\\n\\nPour l\'ensemble de l\'université, la proportion de boursiers du M.E.S.R.I. est de 41 %. La part de boursiers ayant les ressources les plus faibles (échelons 5, 6 ou 7) y est de 13 % contre 21 % en STS.\\n\\nAu sein des universités (hors DUT et filières ingénieurs), les proportions de boursiers diffèrent selon les disciplines universitaires. Les boursiers sont surreprésentés en administration économique et sociale (AES, 55 %) et en langues (51 %). À l\'opposé, la proportion de boursiers dans les disciplines de santé (médecine, odontologie et pharmacie), formations qui durent entre 6 et 12 ans, n\'est que de 25 %. La part de boursiers en DUT est de 45 %.\\n\\n# Plus de 315 000 étudiants boursiers bénéficiaires des repas à 1 euro\\n\\nPour faire face à la crise sanitaire des mesures supplémentaires ont spécifiquement visées les boursiers sur critères sociaux de l\'enseignement supérieur. Les montants des bourses ont été revalorisés à la rentrée 2020 et une aide exceptionnelle de 150 euros a été versée à l\'ensemble des boursiers en décembre 2020. Dès la rentrée, les boursiers ont aussi pu bénéficier de deux repas par jour à 1 euro dans les restaurants universitaires. En janvier 2021, cette aide a été élargie à l\'ensemble des étudiants. Malgré les confinements et les cours en distanciel, plus de 315 000 étudiants boursiers ont pu en bénéficier entre septembre 2020 et juin 2021, soit plus de quatre boursiers sur dix.\\n\\nLe ticket repas à 1 euro a été pérennisé comme un droit connexe aux BCS en juillet 2021.\\n\\n## HERY PAPAGIORGIOU MESRI\\n\\n![img-0.jpeg](img-0.jpeg)\\nLecture : 54,9 % des étudiants en AES ont une BCS dont 24,7 % aux échelons 5, 6 et 7\\nSource : MESRI-SIES / Système d\'information AGLAE, extraction 15/03/2021\\n\\n","images":[{"id":"img-0.jpeg","top_left_x":90,"top_left_y":1325,"bottom_right_x":1590,"bottom_right_y":2153,"image_base64":null,"image_annotation":null}],"dimensions":{"dpi":200,"height":2338,"width":1653},"tables":[],"hyperlinks":[],"header":null,"footer":"MESRI-SIES / Systèmes d\'information et études statistiques\\n\\nDirectrice de la publication : Pierrette Schuhl\\n\\nISSN 2108-4033\\n\\nNote Flash n°20 – septembre 2021"}],"model":"mistral-ocr-latest","usage_info":{"pages_processed":2,"doc_size_bytes":850251},"document_annotation":null}'

In [84]:
data.keys()

dict_keys(['pages', 'model', 'usage_info', 'document_annotation'])

In [93]:
data.get("model")

'mistral-ocr-latest'

In [99]:
data.get("pages")[1]

{'index': 1,
 'markdown': "# Plus de la moitié des étudiants en STS sont boursiers\n\nSelon la filière et le type d'établissement, la proportion de boursiers sur critères sociaux est très variable. Plus de la moitié des étudiants dans les sections de technicien supérieur et assimilés (STS) sont boursiers (55 %) et moins de trois sur dix en classes préparatoires aux grandes écoles (CPGE). La part des boursiers des formations d'ingénieurs diffère selon qu'elles soient universitaires (34 %) ou non (23 %). Les écoles de commerce sont les formations accueillant le moins d'étudiants boursiers (12 %).\n\n## Boursiers sur critères sociaux selon la formation suivie\n\n|   | % de boursiers | Effectifs | % de boursières parmi les étudiants  |\n| --- | --- | --- | --- |\n|  Université | 41,0 | 532 594 | 43,1  |\n|  dont : Préparation DUT | 45,2 | 49 579 | 49,0  |\n|  Filières ingénieurs | 34,0 | 8 373 | 32,4  |\n|  Univ. hors DUT et Ingé. | 40,8 | 474 642 | 42,8  |\n|  CPGE | 27,3 | 22 435 | 27,8  |\n|  dont : secteur public | 29,1 | 20 114 | 29,5  |\n|  secteur privé | 17,9 | 2 321 | 17,5  |\n|  STS et assimilées | 54,9 | 119 934 | 60,1  |\n|  dont : secteur public | 58,1 | 94 796 | 64,0  |\n|  secteur privé | 45,5 | 25 138 | 49,8  |\n|  Form. d'ingénieurs hors univ. | 22,8 | 20 231 | 23,2  |\n|  Écoles de commerce | 12,4 | 17 476 | 13,2  |\n|  Grands étab. de type univ. | 23,3 | 6 263 | 25,7  |\n|  Étab. d'enseignement univ. privés | 27,4 | 8 918 | 28,7  |\n|  Autres écoles | 27,1 | 17 565 | 33,2  |\n|  Scolarité à l'étranger (1) | - | 4 146 | -  |\n|  Total bourses | 38,4 | 749 562 | 41,0  |\n|  dont : secteur public | 41,2 | 675 340 | 43,5  |\n|  secteur privé | 22,4 | 70 076 | 25,4  |\n\n(1) : Il s'agit d'étudiants qui perçoivent une BCS en étant inscrit dans un établissement d'enseignement supérieur étranger\nSource : MESRI-SIES / Système d'information AGLAE, extraction 15/03/2021\n\nPour l'ensemble de l'université, la proportion de boursiers du M.E.S.R.I. est de 41 %. La part de boursiers ayant les ressources les plus faibles (échelons 5, 6 ou 7) y est de 13 % contre 21 % en STS.\n\nAu sein des universités (hors DUT et filières ingénieurs), les proportions de boursiers diffèrent selon les disciplines universitaires. Les boursiers sont surreprésentés en administration économique et sociale (AES, 55 %) et en langues (51 %). À l'opposé, la proportion de boursiers dans les disciplines de santé (médecine, odontologie et pharmacie), formations qui durent entre 6 et 12 ans, n'est que de 25 %. La part de boursiers en DUT est de 45 %.\n\n# Plus de 315 000 étudiants boursiers bénéficiaires des repas à 1 euro\n\nPour faire face à la crise sanitaire des mesures supplémentaires ont spécifiquement visées les boursiers sur critères sociaux de l'enseignement supérieur. Les montants des bourses ont été revalorisés à la rentrée 2020 et une aide exceptionnelle de 150 euros a été versée à l'ensemble des boursiers en décembre 2020. Dès la rentrée, les boursiers ont aussi pu bénéficier de deux repas par jour à 1 euro dans les restaurants universitaires. En janvier 2021, cette aide a été élargie à l'ensemble des étudiants. Malgré les confinements et les cours en distanciel, plus de 315 000 étudiants boursiers ont pu en bénéficier entre septembre 2020 et juin 2021, soit plus de quatre boursiers sur dix.\n\nLe ticket repas à 1 euro a été pérennisé comme un droit connexe aux BCS en juillet 2021.\n\n## HERY PAPAGIORGIOU MESRI\n\n![img-0.jpeg](img-0.jpeg)\nLecture : 54,9 % des étudiants en AES ont une BCS dont 24,7 % aux échelons 5, 6 et 7\nSource : MESRI-SIES / Système d'information AGLAE, extraction 15/03/2021\n\n",
 'images': [{'id': 'img-0.jpeg',
   'top_left_x': 90,
   'top_left_y': 1325,
   'bottom_right_x': 1590,
   'bottom_right_y': 2153,
   'image_base64': None,
   'image_annotation': None}],
 'dimensions': {'dpi': 200, 'height': 2338, 'width': 1653},
 'tables': [],
 'hyperlinks': [],
 'header': None,
 'footer': "MESRI-SIES / Systèmes d'information et études statistiques\n\nDirectrice de la publication : Pierrette Schuhl\n\nISSN 2108-4033\n\nNote Flash n°20 – septembre 2021"}

In [91]:
print(
    "MINISTÈRE\nDE L'ENSEIGNEMENT\nSUPÉRIEUR,\nDE LA RECHERCHE\nET DE L'INNOVATION\n\nLiberté\nÉgalité\nFraternité\n\nNOTE FLASH DU\nSIES\nEnseignement supérieur, Recherche, Innovation\nN° 20\nSeptembre 2021\n\n# Les boursiers sur critères sociaux en 2020-2021\n\nDurant l'année universitaire 2020-2021, marquée par la crise sanitaire, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du M.E.S.R.I., soit une hausse de plus de 4 % en 1 an. Cette hausse atteint 7 % pour les étudiants ayant les plus faibles ressources. La proportion de boursiers au sein des formations ouvrant droit aux bourses dépasse 38 %, taux en hausse annuelle de 1,6 point après 4 années de baisse. De nouvelles aides à destination des boursiers ont été créées au cours de l'année pour faire face au prolongement de la crise. Entre septembre 2020 et juin 2021, plus de 315 000 étudiants boursiers ont bénéficié de l'une d'elles : le ticket repas à 1 euro. Cette aide a été pérennisée comme un droit connexe aux BCS en juillet 2021.\n\n## En 2020-2021, 750 000 étudiants boursiers\n\nDurant l'année universitaire 2020-2021, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du ministère de l'enseignement supérieur, de la recherche et de l'innovation¹ (M.E.S.R.I.). Ces bourses ne peuvent être attribuées qu'aux étudiants inscrits dans une formation habilitée par le ministère en charge de l'enseignement supérieur à recevoir des boursiers, avec des conditions sur l'âge, le régime d'inscription, la nationalité et le diplôme.\n\nElles sont accordées en fonction des ressources et des charges de la famille appréciées selon un barème national qui détermine le montant annuel de la bourse. L'échelon 7, échelon pour les ressources les plus faibles, correspond à une bourse de 5 679 € annuels et concerne 7,5 % des boursiers. Près d'un tiers des boursiers ont une bourse supérieure à 4 610 €, ce montant est supérieur à 2 571 € pour plus de la moitié des boursiers. Enfin, 32 % des boursiers sont à l'échelon 0 et bénéficient d'une aide de 1 032 €.\n\n### Effectifs de boursiers sur critères sociaux\n\n|   | Montant annuel en euros * | Effectifs | % | % de femmes  |\n| --- | --- | --- | --- | --- |\n|  Echelon 0 | 1 032 | 238 162 | 31,8 | 56,8  |\n|  Echelon 1 | 1 707 | 105 137 | 14,0 | 57,6  |\n|  Echelon 2 | 2 571 | 55 004 | 7,3 | 58,1  |\n|  Echelon 3 | 3 292 | 55 578 | 7,4 | 58,8  |\n|  Echelon 4 | 4 015 | 53 554 | 7,1 | 58,7  |\n|  Echelon 5 | 4 610 | 97 850 | 13,1 | 59,3  |\n|  Echelon 6 | 4 889 | 88 185 | 11,8 | 59,8  |\n|  Echelon 7 | 5 679 | 56 092 | 7,5 | 61,0  |\n|  Total |  | 749 562 | 100 | 58,3  |\n|  Aide au mérite | 900 | 45 353 | 6,1 | 64,1  |\n\n* Les montants des BCS ne prennent pas en compte le supplément de 150 euros versé aux boursiers en décembre 2020 en raison de la crise sanitaire.\nSource : MESRI-SIES / Système d'information AGLAE, extraction 15/03/2021\n\nPour les bacheliers bénéficiant d'une BCS et ayant eu une mention « Très bien », une aide au mérite vient compléter la BCS durant trois ans. En 2020, cette aide était de 900 €.\n\n## 38,4 % de boursiers, en hausse de 1,6 point\n\nLe nombre de boursiers a augmenté de plus de 4,4 % en un an, une hausse deux fois plus importante que celle des inscriptions à la rentrée 2020². Cette augmentation atteint 6,9 % au sein des échelons 5, 6 et 7 qui concernent les étudiants ayant les ressources les plus faibles. La part des étudiants boursiers dans les formations ouvrant droit à une bourse du M.E.S.R.I. est de 38,4 % en 2020-2021. En baisse depuis 4 ans, ce taux augmente fortement cette année (+1,6 point), dépassant la part de boursiers observée à la rentrée 2015 (37,9 %).\n\nDes disparités par académie et par genre persistent. La part de boursiers est très élevée en Outre-mer (de 46 à 63 %). Par contraste, environ un tiers des étudiants des académies de Strasbourg et Lyon sont boursiers, et seulement d'un peu plus d'un quart dans les académies de Paris et Versailles. La part de boursiers dans une académie dépend non seulement du niveau de vie des familles mais aussi de l'offre de formation.\n\nParmi l'ensemble des étudiantes, quatre sur dix sont boursières. C'est le cas d'un étudiant sur trois. Cet écart s'explique par une plus forte propension des femmes à poursuivre des études dans les milieux les plus modestes. Elles sont d'ailleurs plus nombreuses parmi les échelons les plus élevés où elles représentent 60 % des boursiers contre 57 % à l'échelon 0. Des disparités se retrouvent aussi selon les formations : on observe davantage de boursières que de boursiers en STS (+5 points) et en IUT (+4 points) ; l'écart est moindre en CPGE, dans les écoles d'ingénieur ou de commerce qui accueillent moins d'étudiants boursiers.\n\nNote Flash n°20 – septembre 2021\n\n1 Les étudiants peuvent bénéficier d'autres aides, non prises en compte ici : aides spécifiques ponctuelles du MESRI, bourses d'établissement et des autres ministères. Les aides spécifiques ponctuelles (ASP), ouvertes aux étudiants boursiers ou non, varient fortement selon la conjoncture. En lien avec la crise sanitaire, de septembre 2020 à avril 2021, le nombre de bénéficiaires par mois était, en moyenne, de 43 % plus élevé que l'année précédente. Le montant des aides allouées a progressé de 57 % sur la même période.\n2 Entre les rentrées 2019 et 2020, le nombre des inscriptions dans l'ensemble de l'enseignement supérieur a progressé de 2,1 % (formations non éligibles aux BCS du MESRI comprises)"
)

MINISTÈRE
DE L'ENSEIGNEMENT
SUPÉRIEUR,
DE LA RECHERCHE
ET DE L'INNOVATION

Liberté
Égalité
Fraternité

NOTE FLASH DU
SIES
Enseignement supérieur, Recherche, Innovation
N° 20
Septembre 2021

# Les boursiers sur critères sociaux en 2020-2021

Durant l'année universitaire 2020-2021, marquée par la crise sanitaire, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du M.E.S.R.I., soit une hausse de plus de 4 % en 1 an. Cette hausse atteint 7 % pour les étudiants ayant les plus faibles ressources. La proportion de boursiers au sein des formations ouvrant droit aux bourses dépasse 38 %, taux en hausse annuelle de 1,6 point après 4 années de baisse. De nouvelles aides à destination des boursiers ont été créées au cours de l'année pour faire face au prolongement de la crise. Entre septembre 2020 et juin 2021, plus de 315 000 étudiants boursiers ont bénéficié de l'une d'elles : le ticket repas à 1 euro. Cette aide a été pérennisée comme un droit connexe aux BCS en juillet 2021.

## En 2020-2021, 750 000 étudiants boursiers

Durant l'année universitaire 2020-2021, 750 000 étudiants ont perçu une bourse sur critères sociaux (BCS) du ministère de l'enseignement supérieur, de la recherche et de l'innovation¹ (M.E.S.R.I.). Ces bourses ne peuvent être attribuées qu'aux étudiants inscrits dans une formation habilitée par le ministère en charge de l'enseignement supérieur à recevoir des boursiers, avec des conditions sur l'âge, le régime d'inscription, la nationalité et le diplôme.

Elles sont accordées en fonction des ressources et des charges de la famille appréciées selon un barème national qui détermine le montant annuel de la bourse. L'échelon 7, échelon pour les ressources les plus faibles, correspond à une bourse de 5 679 € annuels et concerne 7,5 % des boursiers. Près d'un tiers des boursiers ont une bourse supérieure à 4 610 €, ce montant est supérieur à 2 571 € pour plus de la moitié des boursiers. Enfin, 32 % des boursiers sont à l'échelon 0 et bénéficient d'une aide de 1 032 €.

### Effectifs de boursiers sur critères sociaux

|   | Montant annuel en euros * | Effectifs | % | % de femmes  |
| --- | --- | --- | --- | --- |
|  Echelon 0 | 1 032 | 238 162 | 31,8 | 56,8  |
|  Echelon 1 | 1 707 | 105 137 | 14,0 | 57,6  |
|  Echelon 2 | 2 571 | 55 004 | 7,3 | 58,1  |
|  Echelon 3 | 3 292 | 55 578 | 7,4 | 58,8  |
|  Echelon 4 | 4 015 | 53 554 | 7,1 | 58,7  |
|  Echelon 5 | 4 610 | 97 850 | 13,1 | 59,3  |
|  Echelon 6 | 4 889 | 88 185 | 11,8 | 59,8  |
|  Echelon 7 | 5 679 | 56 092 | 7,5 | 61,0  |
|  Total |  | 749 562 | 100 | 58,3  |
|  Aide au mérite | 900 | 45 353 | 6,1 | 64,1  |

* Les montants des BCS ne prennent pas en compte le supplément de 150 euros versé aux boursiers en décembre 2020 en raison de la crise sanitaire.
Source : MESRI-SIES / Système d'information AGLAE, extraction 15/03/2021

Pour les bacheliers bénéficiant d'une BCS et ayant eu une mention « Très bien », une aide au mérite vient compléter la BCS durant trois ans. En 2020, cette aide était de 900 €.

## 38,4 % de boursiers, en hausse de 1,6 point

Le nombre de boursiers a augmenté de plus de 4,4 % en un an, une hausse deux fois plus importante que celle des inscriptions à la rentrée 2020². Cette augmentation atteint 6,9 % au sein des échelons 5, 6 et 7 qui concernent les étudiants ayant les ressources les plus faibles. La part des étudiants boursiers dans les formations ouvrant droit à une bourse du M.E.S.R.I. est de 38,4 % en 2020-2021. En baisse depuis 4 ans, ce taux augmente fortement cette année (+1,6 point), dépassant la part de boursiers observée à la rentrée 2015 (37,9 %).

Des disparités par académie et par genre persistent. La part de boursiers est très élevée en Outre-mer (de 46 à 63 %). Par contraste, environ un tiers des étudiants des académies de Strasbourg et Lyon sont boursiers, et seulement d'un peu plus d'un quart dans les académies de Paris et Versailles. La part de boursiers dans une académie dépend non seulement du niveau de vie des familles mais aussi de l'offre de formation.

Parmi l'ensemble des étudiantes, quatre sur dix sont boursières. C'est le cas d'un étudiant sur trois. Cet écart s'explique par une plus forte propension des femmes à poursuivre des études dans les milieux les plus modestes. Elles sont d'ailleurs plus nombreuses parmi les échelons les plus élevés où elles représentent 60 % des boursiers contre 57 % à l'échelon 0. Des disparités se retrouvent aussi selon les formations : on observe davantage de boursières que de boursiers en STS (+5 points) et en IUT (+4 points) ; l'écart est moindre en CPGE, dans les écoles d'ingénieur ou de commerce qui accueillent moins d'étudiants boursiers.

Note Flash n°20 – septembre 2021

1 Les étudiants peuvent bénéficier d'autres aides, non prises en compte ici : aides spécifiques ponctuelles du MESRI, bourses d'établissement et des autres ministères. Les aides spécifiques ponctuelles (ASP), ouvertes aux étudiants boursiers ou non, varient fortement selon la conjoncture. En lien avec la crise sanitaire, de septembre 2020 à avril 2021, le nombre de bénéficiaires par mois était, en moyenne, de 43 % plus élevé que l'année précédente. Le montant des aides allouées a progressé de 57 % sur la même période.
2 Entre les rentrées 2019 et 2020, le nombre des inscriptions dans l'ensemble de l'enseignement supérieur a progressé de 2,1 % (formations non éligibles aux BCS du MESRI comprises)

In [116]:
import re
from dataclasses import dataclass, field


def table_to_dict(raw: str):
    lines = [line.strip() for line in raw.strip().splitlines()]
    # Remove separator line
    lines = [line for line in lines if not re.match(r"^\|[-:\s|]+\|$", line)]

    rows = []
    for line in lines:
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        rows.append(cells)

    if not rows:
        return None

    headers = rows[0]
    data = rows[1:]

    return {"headers": headers, "data": data}


@dataclass
class Section:
    level: int  # 1=title, 2=h2, 3=h3
    title: str
    paragraphs: list[str] = field(default_factory=list)
    tables: list[str] = field(default_factory=list)  # raw markdown table strings


def parse_markdown(md: str) -> list[Section]:
    sections: list[Section] = []
    current: Section | None = None
    buffer: list[str] = []

    def flush_buffer():
        if current is None or not buffer:
            return
        block = "\n".join(buffer).strip()
        if not block:
            return

        # Split block into chunks separated by blank lines
        for chunk in re.split(r"\n{2,}", block):
            chunk = chunk.strip()
            if not chunk:
                continue

            lines = chunk.splitlines()
            # A table has at least one | and a separator line with ---
            is_table = any("|" in line for line in lines) and any(re.match(r"^\s*\|[\s\-|:]+\|\s*$", line) for line in lines)

            if is_table:
                current.tables.append(table_to_dict(chunk))
            else:
                if chunk:
                    current.paragraphs.append(chunk)
        buffer.clear()

    for line in md.splitlines():
        heading = re.match(r"^(#{1,3})\s+(.*)", line)
        if heading:
            flush_buffer()
            level = len(heading.group(1))
            title = heading.group(2).strip()
            current = Section(level=level, title=title)
            sections.append(current)
        else:
            if current is not None:
                buffer.append(line)

    flush_buffer()
    return sections

In [117]:
md = data.get("pages")[0].get("markdown")
sections = parse_markdown(md)

In [119]:
sections[2].tables

[{'headers': ['',
   'Montant annuel en euros *',
   'Effectifs',
   '%',
   '% de femmes'],
  'data': [['Echelon 0', '1 032', '238 162', '31,8', '56,8'],
   ['Echelon 1', '1 707', '105 137', '14,0', '57,6'],
   ['Echelon 2', '2 571', '55 004', '7,3', '58,1'],
   ['Echelon 3', '3 292', '55 578', '7,4', '58,8'],
   ['Echelon 4', '4 015', '53 554', '7,1', '58,7'],
   ['Echelon 5', '4 610', '97 850', '13,1', '59,3'],
   ['Echelon 6', '4 889', '88 185', '11,8', '59,8'],
   ['Echelon 7', '5 679', '56 092', '7,5', '61,0'],
   ['Total', '', '749 562', '100', '58,3'],
   ['Aide au mérite', '900', '45 353', '6,1', '64,1']]}]